site_name: Lumito's documentation
site_description: "Lumito's documentation"
site_author: 'Lumito'
docs_dir: docs
repo_url: 'https://github.com/LumitoLuma/lumitoluma.github.io'
nav:
    - Home: index.md
theme:
  name: 'material'
  highlightjs: true
  hljs_languages:
      - c