site_name: Lumito's documentation
site_description: (WIP) Lumito's programs and services documentation
site_author: Lumito
docs_dir: docs
repo_url: https://github.com/LumitoLuma/docs

nav:
    - Home: index.md
    - Repos:
      - OpenSSH for Windows: repos/OpenSSH-for-Windows.md
      - Program Overflow: repos/ProgramOverflow.md

theme:
  name: material
  icon:
    logo: material/code-tags
  favicon: icons/favicon.png
  palette:
    scheme: slate
    primary: green
    accent: teal
  features:
    - navigation.instant
    - navigation.tabs

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.lumito.net
      name: LumitoLuma's website
    - icon: fontawesome/brands/github
      link: https://github.com/LumitoLuma
      name: LumitoLuma on GitHub
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/13248902/lumito
      name: LumitoLuma on StackOverflow

copyright: Copyright &copy; 2021, <a href="https://www.lumito.net" target="_blank">Lumito</a>
