site_name: Lumito's documentation
site_description: "(WIP) Lumito's programs and services documentation"
site_author: 'Lumito'
docs_dir: docs
repo_url: 'https://github.com/LumitoLuma/docs'

nav:
    - About: index.md

theme:
  name: 'material'
  icon:
    logo: material/code-tags
  favicon: icons/favicon.png
  palette:
    scheme: slate
    primary: green
    accent: teal
  features:
    - navigation.instant
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LumitoLuma
      name: LumitoLuma on GitHub

copyright: Copyright &copy; 2021, <a href="https://www.lumito.net" target="_blank">Lumito</a>